### ISSUE TITLE
Energy Buffer Crashes

### ISSUE THREAD

**Issue by genuinelymiffed** [BuiltBrokenModding/ICBM-Classic#205] opened 2019-02-23 06:58 UTC
My friends and I are running a modded server, with ICBM classic being a more recent addition. For the most part it's working fine, bombs and launch pads work, but whenever we place a radar, launch panel, or EMP tower (potentially more, those are just the ones we've confirmed) it crashes the server, including singleplayer worlds, and prevents the worlds from loading until the block has been removed. The crash report is always this:
The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: icbm.classic.prefab.TileICBMMachine.getEnergyBuffer(Lnet/minecraftforge/common/util/ForgeDirection;)Lcom/builtbroken/mc/framework/energy/data/EnergyBuffer;
with the exception of the Radar, which says the game crashed while RENDERING block entity.

Crash reports for both versions are attatched, would appreciate any advice on how to fix this
[(radar) crash-2019-02-22_22.57.05-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/2896562/radar.crash-2019-02-22_22.57.05-client.txt)

[(EMP tower) crash-2019-02-22_22.52.01-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/2896558/EMP.tower.crash-2019-02-22_22.52.01-client.txt)

**Comment by DarkGuardsman** [comment] 2019-02-23 16:46
Duplicate of https://github.com/BuiltBrokenModding/ICBM-Classic/issues/194

**Closed as completed by DarkGuardsman** 2019-02-23 16:46 UTC
Labels: duplicate

**Comment by genuinelymiffed** [comment] 2019-02-23 21:18
I fixed it so I have ICBM-classic-1.7.10-2.16.3b225 and VoltzEngine-1.7.10-1.11.0b489 but it's still crashing, only change I can find is that it says it crashed while ticking world now if I use the launch controller.
Radar:
The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.NoSuchMethodError: icbm.classic.prefab.TileICBMMachine.getEnergyBuffer(Lnet/minecraftforge/common/util/ForgeDirection;)Lcom/builtbroken/mc/framework/energy/data/EnergyBuffer;
Launch Controller:
The game crashed whilst exception ticking world
The game crashed whilst exception ticking world
Error: java.lang.NoSuchMethodError: icbm.classic.prefab.TileICBMMachine.getEnergyBuffer(Lnet/minecraftforge/common/util/ForgeDirection;)Lcom/builtbroken/mc/framework/energy/data/EnergyBuffer;
[launch controller t3 crash-2019-02-23_13.17.27-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/2897274/launch.controller.t3.crash-2019-02-23_13.17.27-server.txt)
