### ISSUE TITLE
ICBM minecraft 1.7.10 Homing Missile Issue

### ISSUE THREAD

**Issue by metsatahe** [BuiltBrokenModding/ICBM-Classic#249] opened 2019-10-26 20:36 UTC
I left clicked on a villager to make the tracker track him which works perfectly. But when going up to my Homing Missile and right clicking it, it makes me ride the rocket, but wont lock to the tracker coordinates. Am I doing something completely wrong?

**Comment by GHXX** [comment] 2020-03-26 14:19
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.

This is also a duplicate of #102

**Closed as completed by GHXX** 2020-03-26 14:19 UTC
Labels: Old: 1.7.10
