### ISSUE TITLE
[1.12] Desync with regen blast

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#107] opened 2018-03-26 18:07 UTC
Regen blast seems to cause some desync issues on chunks. This can cause the chunk data to not update and not be sent to the client. Most noticeable after regenerating a chunk then breaking blocks. Block breaks will not be sent to the client.

**Comment by DarkGuardsman** [comment] 2019-02-12 19:39
https://trello.com/c/q2lzQ2EQ/60-fix-icbm-classic-regen-missile-10

**Comment by GHXX** [comment] 2019-08-28 02:03
duplicate of #191 btw

**Comment by DarkGuardsman** [comment] 2019-08-28 11:35
lol the other ticket is a duplicate, this is the older of the two. Either way we no longer have the regen blast in the rewrite. Its too much of a pain to support so its being removed.

**Closed as completed** 2019-08-28 11:36 UTC
Labels: bug

**Comment by GHXX** [comment] 2019-08-28 20:46
The other one had more info though 😛
