### ISSUE TITLE
No visuals for chemical weapons

### ISSUE THREAD

**Issue by SwilaPlasmark** [BuiltBrokenModding/ICBM-Classic#347] opened 2021-02-22 08:28 UTC
Is this a known issue or simply something thats on the to do list?

**Comment by DarkGuardsman** [comment] 2021-04-20 10:06
Most likely particle settings. Can you check if it will work in a new world?

**Comment by GHXX** [comment] 2021-08-12 20:40
Im assuming you are referring to chemical explosives not showing any particles after exploding? 
(When playing on a multiplayer server) In this case this would be a duplicate of #362

**Closed as completed** 2021-10-06 17:19 UTC
Labels: defect, more info needed
