### ISSUE TITLE
Cruise launcher hides your inventory when you open its GUI. 

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM-Classic#231] opened 2019-07-12 19:50 UTC
when you open cruise launcher gui it hides your inventory and is like if your inventory is empty, but if you click where the items are, you can select them. 

here's before opening gui 
https://gyazo.com/297444525cfec5f1fa9dd759f223e836

heres after opening gui
https://gyazo.com/9844a2a67d314fcba74986e10b6e61e4

Thanks.

**Comment by DarkGuardsman** [comment] 2019-07-13 17:25
Will look into after we finish the current rewrite... might already even be fixed.

**Comment by LemADEC** [comment] 2019-07-26 23:22
Can't reproduce in dev, please list your mods.

**Comment by DarkGuardsman** [comment] 2019-07-27 18:36
Its likely an edge case already fixed in the rewrite. I think it was a leaking openGL conflicting with JEI or some other overlap.

**Comment by GHXX** [comment] 2020-01-02 19:25
Merged blast-rewrite into 1.12

**Closed as completed by GHXX** 2020-01-02 19:25 UTC
