### ISSUE TITLE
Server Crash after launching missile

### ISSUE THREAD

**Issue by voidswrath** [BuiltBrokenModding/ICBM-Classic#339] opened 2020-11-18 17:31 UTC
Launched a high veolicty tier 2 missile and server closed with this crash report.

https://pastebin.com/YFYAYg3J

**Comment by clienthax** [comment] 2020-11-19 08:42
Dupe of https://github.com/BuiltBrokenModding/ICBM-Classic/issues/295

**Closed as completed by clienthax** 2020-11-19 08:42 UTC
