### ISSUE TITLE
Game crash with missile launchers

### ISSUE THREAD

**Issue by apuerto11** [BuiltBrokenModding/ICBM-Classic#42] opened 2017-02-21 14:50 UTC
When I put a missile launcher base it make my game crash.
Here is the crash report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2/21/17 3:48 PM
Description: Ticking block entity

java.lang.AbstractMethodError: com.builtbroken.mc.prefab.tile.multiblock.EnumMultiblock$$Lambda$26/2041142558.func_149915_a(Lnet/minecraft/world/World;I)Lnet/minecraft/tileentity/TileEntity;
	at com.builtbroken.mc.prefab.tile.multiblock.EnumMultiblock.newTile(EnumMultiblock.java:73)
	at com.builtbroken.mc.prefab.tile.multiblock.EnumMultiblock.provideTile(EnumMultiblock.java:86)
	at com.builtbroken.mc.prefab.tile.multiblock.BlockMultiblock.func_149915_a(BlockMultiblock.java:255)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at com.builtbroken.mc.prefab.tile.multiblock.MultiBlockHelper.buildMultiBlock(MultiBlockHelper.java:111)
	at icbm.classic.content.machines.launcher.base.TileLauncherBase.firstTick(TileLauncherBase.java:369)
	at com.builtbroken.mc.prefab.tile.Tile.func_145845_h(Tile.java:189)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.builtbroken.mc.prefab.tile.multiblock.EnumMultiblock.newTile(EnumMultiblock.java:73)
	at com.builtbroken.mc.prefab.tile.multiblock.EnumMultiblock.provideTile(EnumMultiblock.java:86)
	at com.builtbroken.mc.prefab.tile.multiblock.BlockMultiblock.func_149915_a(BlockMultiblock.java:255)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at com.builtbroken.mc.prefab.tile.multiblock.MultiBlockHelper.buildMultiBlock(MultiBlockHelper.java:111)
	at icbm.classic.content.machines.launcher.base.TileLauncherBase.firstTick(TileLauncherBase.java:369)
	at com.builtbroken.mc.prefab.tile.Tile.func_145845_h(Tile.java:189)

-- Block entity being ticked --
Details:
	Name: icbmclassic:icbmCLauncherBase // icbm.classic.content.machines.launcher.base.TileLauncherBaseClient
	Block type: ID #181 (tile.icbmclassic:launcherBase // com.builtbroken.mc.prefab.tile.BlockTile)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (251,64,-81), Chunk: (at 11,4,15 in 15,-6; contains blocks 240,0,-96 to 255,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #181 (tile.icbmclassic:launcherBase // com.builtbroken.mc.prefab.tile.BlockTile)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['SirRedstone'/16, l='MpServer', x=251.33, y=65.62, z=-82.15]]
	Chunk stats: MultiplayerChunkCache: 620, 620
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (231,4,-117), Chunk: (at 7,0,11 in 14,-8; contains blocks 224,0,-128 to 239,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 673 game time, 673 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityZombie['Zombie'/15756, l='MpServer', x=306.50, y=26.00, z=-73.50], EntityItem['item.tile.flower1.dandelion'/11538, l='MpServer', x=261.75, y=64.13, z=-70.56], EntityClientPlayerMP['SirRedstone'/16, l='MpServer', x=251.33, y=65.62, z=-82.15], EntitySquid['Squid'/948, l='MpServer', x=238.36, y=62.04, z=-77.11], EntitySquid['Squid'/949, l='MpServer', x=237.23, y=61.34, z=-77.50], EntitySquid['Squid'/950, l='MpServer', x=233.49, y=61.00, z=-69.42], EntitySquid['Squid'/55, l='MpServer', x=277.50, y=61.00, z=-112.50], EntityItem['item.tile.flower2.houstonia'/823, l='MpServer', x=255.22, y=64.13, z=-73.28], EntitySquid['Squid'/951, l='MpServer', x=233.99, y=61.00, z=-70.63], EntitySquid['Squid'/56, l='MpServer', x=278.66, y=61.25, z=-115.19], EntitySquid['Squid'/952, l='MpServer', x=233.47, y=60.29, z=-73.92], EntityPig['Pig'/13376, l='MpServer', x=301.28, y=64.00, z=-24.88], EntityItem['item.tile.flower2.poppy'/15424, l='MpServer', x=231.38, y=62.13, z=-72.25], EntityPig['Pig'/13377, l='MpServer', x=296.50, y=64.00, z=-21.50], EntityPig['Pig'/13378, l='MpServer', x=296.50, y=64.00, z=-23.50], EntityPig['Pig'/13379, l='MpServer', x=295.50, y=64.00, z=-26.50], EntityCow['Cow'/13380, l='MpServer', x=307.06, y=64.00, z=-19.63], EntityCow['Cow'/13381, l='MpServer', x=308.22, y=64.00, z=-19.50], EntityCow['Cow'/13382, l='MpServer', x=309.78, y=64.00, z=-19.50], EntityCow['Cow'/13383, l='MpServer', x=319.78, y=64.00, z=-16.81], EntityCow['Cow'/13384, l='MpServer', x=306.06, y=64.00, z=-18.09], EntityCow['Cow'/13385, l='MpServer', x=302.88, y=64.00, z=-22.88], EntityCow['Cow'/13386, l='MpServer', x=305.44, y=64.00, z=-22.44], EntityCow['Cow'/13387, l='MpServer', x=306.78, y=64.00, z=-23.78], EntitySheep['Sheep'/13388, l='MpServer', x=274.50, y=64.00, z=-27.50], EntitySheep['Sheep'/13389, l='MpServer', x=276.50, y=64.00, z=-27.50], EntitySheep['Sheep'/13390, l='MpServer', x=273.50, y=64.00, z=-25.50], EntitySheep['Sheep'/13391, l='MpServer', x=276.50, y=64.00, z=-30.50], EntitySheep['Sheep'/13392, l='MpServer', x=274.50, y=64.00, z=-32.50], EntitySheep['Sheep'/13393, l='MpServer', x=264.03, y=64.00, z=-27.97], EntitySheep['Sheep'/13394, l='MpServer', x=268.50, y=64.00, z=-36.50], EntitySheep['Sheep'/13395, l='MpServer', x=266.50, y=64.00, z=-37.50], EntityChicken['Chicken'/13396, l='MpServer', x=274.50, y=64.00, z=-28.50], EntityChicken['Chicken'/13397, l='MpServer', x=273.50, y=64.00, z=-28.50], EntityChicken['Chicken'/13398, l='MpServer', x=275.50, y=64.00, z=-26.50], EntityChicken['Chicken'/13399, l='MpServer', x=274.50, y=64.00, z=-24.50], EntityItem['item.tile.flower1.dandelion'/10078, l='MpServer', x=260.50, y=63.13, z=-69.31], EntityItem['item.item.seeds'/1377, l='MpServer', x=230.25, y=64.13, z=-67.13], EntityBat['Bat'/12641, l='MpServer', x=232.61, y=43.00, z=-55.81], EntityBat['Bat'/22008, l='MpServer', x=234.48, y=43.00, z=-55.18], EntityBat['Bat'/22009, l='MpServer', x=230.11, y=43.22, z=-54.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 646874400 bytes (616 MB) / 925368320 bytes (882 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	VoltzEngine{0.28.2.356} [Voltz Engine] (VoltzEngine-1.7.10-0.28.2b356-dev-universal.jar) 
	UCHIJAAAA	icbmclassic{2.15.1.62} [ICBM-Classic] (ICBM-classic-1.7.10-2.15.1b62-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 315M/PCIe/SSE2'
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: GeForce 315M/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by DarkGuardsman** [comment] 2017-02-21 16:56
Duplicate of https://github.com/BuiltBrokenModding/ICBM-Classic/issues/41

The issue has been fixed, an alpha release is already up on curse for download. You will need to download Voltz Engine as well since it contains the actual fix to the problem.

I will close this issue once we release the build as non-alpha on Friday just in case others have the same issue.

**Comment by apuerto11** [comment] 2017-02-21 19:25
Thank you, I will check this out

**Closed as completed** 2017-03-08 19:51 UTC
