### ISSUE TITLE
Fix:  fix radar

### ISSUE THREAD

**Issue by rldacas** [BuiltBrokenModding/ICBM-Classic#392] opened 2022-05-14 19:13 UTC
I tried to solve the problem myself, nothing happened, the radar works, I go into it and there is no radar point and it doesn’t show anything except green squares, even though there is energy, it launched rockets, it still didn’t work

**Comment by DarkGuardsman** [comment] 2022-05-16 08:41
Duplicate of https://github.com/BuiltBrokenModding/ICBM-Classic/issues/384

**Closed as completed by DarkGuardsman** 2022-05-16 08:41 UTC
