### ISSUE TITLE
Chemical weapon particles not working on pebble host servers

### ISSUE THREAD

**Issue by AlphaWolf3040** [BuiltBrokenModding/ICBM-Classic#358] opened 2021-07-27 21:07 UTC
no matter what ive tried the particles wont show i made sure explosions were turned on, i tried doing this in a single player world and it worked fine, im on 1.12.2 if that helps.

does anyone know how to fix this error/glitch/bug 

i am on a pebble host server btw as title says

**Comment by DarkGuardsman** [comment] 2021-07-28 01:36
Do particles work for other mods?

**Comment by AlphaWolf3040** [comment] 2021-07-28 07:08
> Do particles work for other mods?

I believe so, yes

**Comment by GHXX** [comment] 2021-08-11 05:55
likely a duplicate of #362 and appears to be an issue when running just forge + icbm in a client server environment

**Closed as completed** 2021-10-06 17:21 UTC
Labels: defect, Fix is waiting to be merged
