### ISSUE TITLE
Battery Box/ Cruise Launcher inventory issues

### ISSUE THREAD

**Issue by clienthax** [BuiltBrokenModding/ICBM-Classic#254] opened 2019-11-07 23:08 UTC
blast-rewrite

Battery box makes everything in your inventory invisible, it also has another inventory screen on the bottom right that lets you delete items.

![image](https://user-images.githubusercontent.com/1056270/68435533-6bf1bd80-01b3-11ea-8788-96f8a6c8b971.png)
![image](https://user-images.githubusercontent.com/1056270/68435537-6e541780-01b3-11ea-9528-73f62a66187c.png)
![image](https://user-images.githubusercontent.com/1056270/68435581-85930500-01b3-11ea-9524-290946af3429.png)

**Comment by DarkGuardsman** [comment] 2019-11-07 23:14
Did I even make that thing craftable?

**Comment by clienthax** [comment] 2019-11-07 23:17
> Did I even make that thing craftable?

Battery box is not craftable, cruise launcher is.

**Comment by clienthax** [comment] 2019-11-07 23:23
seems it could be same as https://github.com/BuiltBrokenModding/ICBM-Classic/issues/231
Will have a look once im home.

**Comment by DarkGuardsman** [comment] 2019-11-08 12:08
Ya battery box should be removed when @bl4ckscor3 gets a chance. As for cruise launcher this is a known defect that is caused by a few other mods. We can fix it on our side but its been hard to track down.

**Comment by clienthax** [comment] 2019-11-09 01:20
Seems to be of been resolved by the GLStateManager commit

**Comment by bl4ckscor3** [comment] 2019-11-09 08:18
Good, that was my hunch.

**Comment by GHXX** [comment] 2020-01-02 19:25
Merged blast-rewrite into 1.12

**Closed as completed** 2020-01-02 19:24 UTC
Labels: Fix is waiting to be merged
