### ISSUE TITLE
[1.12] Launcher base mount point entity not despawning

### ISSUE THREAD

**Issue by DatGurney** [BuiltBrokenModding/ICBM-Classic#84] opened 2018-01-29 16:37 UTC
if you break a missile holder with a rocket loaded it is still clickable so you can ride it but is invisible. reappears if you re-place the missile holder

**Comment by dmodoomsirius** [comment] 2018-01-30 00:23
Both VoltzEngine and ICBM Classic are in a very early alpha state. We are aware things are broken.

**Comment by DarkGuardsman** [comment] 2018-01-30 14:01
As a note it's not the missile but the mount point for the launcher. I should have it fixed soon.

**Comment by DatGurney** [comment] 2018-01-30 18:12
yes, understandable that there are broken things. just thought it best to post it to the issue tracker to make it easier to track it. appreciate all the hard work

**Comment by DarkGuardsman** [comment] 2018-01-30 18:28
Thank you, and there is no problem in posting the bug. I rather have you post bugs than not post bugs. Just at the moment, not much is going to be done with bug reports until a beta version is released. As a lot of the bugs are known and will be fixed.

**Comment by GHXX** [comment] 2019-09-01 17:52
i could not reproduce this in the current 1.12 branch, so since this is more than one year old im assuming it has been fixed at some point. If the issue still persists, feel free to comment on here and ill reopen it.

**Closed as completed by GHXX** 2019-09-01 17:52 UTC
Labels: bug, Old: 1.7.10

**Comment by Browniehound** [comment] 2021-01-09 05:54
Hello I am having this same issue with the 1.7.10 2.16.2b205 version, any help?

**Comment by GHXX** [comment] 2021-01-09 18:55
Its very unlikely that 1.7.10 receives further updates, but i added the tag anyway..

**Comment by Browniehound** [comment] 2021-01-09 22:38
alright thanks
