### ISSUE TITLE
ICBM StackOverFlow Error - MC Eternal (Minecraft 1.12.2, Forge 14.23.5.2847)

### ISSUE THREAD

**Issue by Agentomega** [BuiltBrokenModding/ICBM-Classic#316] opened 2020-05-13 06:37 UTC
Not entirely sure how this was caused, but I was in a creative world putting down a large selection of placeable blocks to create a test map for dynmap, and then the world crashed.  Evidently there is an issue that causes TileEntityBattery.getCapability to recurse infinitely (see attached log).

[crash-2020-05-13_02.18.11-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/4620222/crash-2020-05-13_02.18.11-client.txt)

**Comment by GHXX** [comment] 2020-05-13 12:17
This is a duplicate of the already closed issues #253 and #287 , way back in november.
According to the crash log you are running version 1.12.2-3.3.0.63 
Get the latest **alpha** version from curse: https://www.curseforge.com/minecraft/mc-mods/icbm-classic which is "ICBM - Classic 1.12.2-4.0.1b75-UNSTABLE build 75". It will be fixed in there and should be pretty stable.
Let me know how it goes.

**Closed as completed** 2020-05-13 15:19 UTC
