### ISSUE TITLE
Crash when I join a world

### ISSUE THREAD

**Issue by Daudeuf** [BuiltBrokenModding/ICBM-Classic#265] opened 2020-01-04 18:54 UTC
https://paste.dimdev.org/upunelohiv.mccrash

**Comment by bl4ckscor3** [comment] 2020-01-04 20:58
Looks like a Better Foliage/Octarine Core issue.

**Comment by GHXX** [comment] 2020-01-16 17:23
Im closing this one, because the crash report does not mention icbm anywhere in the stacktrace and there has been no further input.

Feel free to reopen this if you manage to reproduce the error consistently, @Daudeuf

**Closed as completed by GHXX** 2020-01-16 17:23 UTC
