### ISSUE TITLE
ICBM CLASSIC >> Chunk Loading

### ISSUE THREAD

**Issue by mesl** [BuiltBrokenModding/ICBM-Classic#70] opened 2017-08-08 15:03 UTC
Hi,

I use icbm-classic for a while now but for instance when i send a rocket 3000 blocks away it will never reach it,

My friends and i were playing with the mod, on a given moment i used a rocket to send it to their base (3500 blocks away) but the rocket never arrived

(and i was wondering if there is a full tutorial on the mod because i don't know how some machines work)

Sorry for the bad english
Kind regards, Merlyn

**Comment by DarkGuardsman** [comment] 2017-08-09 13:32
Your missile is most likely in an unloaded chunk. 

Due to how missiles work in this version of the mod; A missile will physically fly from point A to point B. This means if the area is not loaded the missile will unload like any entity in Minecraft. This is half by design and half due to old code. As the original version worked the same way but did include chunk loading. During the update from 1.6.4 to 1.7.10 chunk loading was removed as it never worked well.

Now there are plans to fix this similar to how the new ICBM works. In which the missile will be removed from the world if not near a player. Then it will be simulated until near the target location. Where it will be added back into the world to give the impression it flew the entire distance.

**Comment by mesl** [comment] 2017-08-12 09:25
Oke, Thanks for your reply

**Comment by LemADEC** [comment] 2017-08-17 14:42
In older version, you could ride the missile to ensure it reach its target.

**Comment by NEXUS2345** [comment] 2018-06-29 02:41
Is there any update on the progress of this change?

**Comment by DarkGuardsman** [comment] 2018-06-29 03:45
Nope

**Comment by GHXX** [comment] 2018-08-05 02:12
Fixed in 113aba638657ff62a9539405e3b524f87c3f4581
Missiles will now be removed from existence at a certain time and then reappear at the target location after some time which depends on the distance it needs to travel.

**Closed as completed by GHXX** 2018-08-05 02:12 UTC
Labels: enhancement
