### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by Zimbrax** [BuiltBrokenModding/ICBM-Classic#153] opened 2018-08-12 19:43 UTC
I have downloaded the ICBM classic mod, for minecraft 1.12.2 but there seems to be missing the actual missiles and explosives. I have the platform and other tools (according to the Not Enough Items mod), but there are no missiles there or explosives so theres no point in having the mod like that. For further information im using other mods like the Mekanism mod to get power.

**Comment by kmecpp** [comment] 2018-08-12 19:47
Possible duplicate of #137

**Comment by DarkGuardsman** [comment] 2018-08-12 23:10
As far as I can tell the search and NEI fail to find the content. The content is there though, it can be found on the mod's creative tab and crafted just fine. I've also been able to find it using JEI just fine.

**Comment by DarkGuardsman** [comment] 2018-08-17 16:23
Ya it works with latest mod and JEI... will test NEI in a bit
![screenshot 2018-08-17 12 20 58](https://user-images.githubusercontent.com/1477330/44277298-3e200200-a218-11e8-94b4-dfbf2e8c0597.png)

**Comment by edgarnunez27** [comment] 2020-04-01 19:03
was this ever resolved ? having the same issue

**Comment by GHXX** [comment] 2020-04-02 00:50
Content is definitely there, @edgarnunez27 what version of the mod are you running, and what inventory-mod (jei / nei / ...)

**Comment by edgarnunez27** [comment] 2020-04-02 01:30
Nevermind it was there wasn't looking at the right tab in-game when searching for it.

**Comment by GHXX** [comment] 2020-04-02 01:34
Alright, glad you found it.

**Closed as completed by GHXX** 2020-04-02 01:34 UTC
Labels: bug, unconfirmed
